# Generated by Django 3.1.8 on 2021-09-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
